import time

nom = str(input("Digues el teu nom de guerra, per començar l'aventura: "))
enemic = str(input("Introdueix un nom per l'enemic: "))
bacteria = str(input("Introdueix un nom per a la bacteria: "))
print(f"Benvingut {nom}, prepara't que surts")#Començament del joc
time.sleep(3)
print(f"Et trobes en una terra posseïda per un esser malvat anomenat {enemic} que ha desplegat una bacteria anomenada {bacteria}, que converteix a les persones en els seus súbdits")
time.sleep(3)
print(f"Un cop creus que t'has contaminat de {bacteria}...")
time.sleep(3)
print("De sobte surten uns bitxos de les clavegueres, que semblen unes tortugues.")
time.sleep(3)
print("Aquestes et subministren una mascareta i un mapa, i de sobte desapareixen.")
time.sleep(3)
print("Mires el mapa i veus que marca una ubicació, creus que és la sortida de la ciutat.")
time.sleep(3)
print("Però...")
time.sleep(3)
print("Et fixes que el mapa està en una altra llengua, sembla una llengua antiga.")
time.sleep(3)
print("Busques al teu mòbil i veus que la llengua és una llengua romana.")
time.sleep(3)
print(f"Gràcies al teu mòbil tradueixes el mapa i aquest conté la localitzaciò d'uns objectes per derrotar en {enemic}.")
time.sleep(3)
print("Un cop estàs a punt d'arribar a la localització...")
time.sleep(3)
print("Surt un jove d'aparença peculiar amb cabell groc i ulls blaus, amb un bastó extensible a l'esquena.")
time.sleep(3)
print("I et diu: En un d'aquests dos camins trobaràs l'èxit, en canvi a l'altre trobaràs la teva perdició, que la sort t'acompanyi.")
time.sleep(3)
print("Un cop arribes als camins has de prendre la decisió que et portarà o no a l'èxit.")
time.sleep(3)
desició = int(input(f"Escull amb saviesa {nom} quin camí esculls? L'1 o el 2: "))

if desició == 1:#Condicional per la decisio
    print("Vas caminant pel camí número 1 i de sobte...")
    time.sleep(3)
    print("El terra es mou d'una manera poc peculiar, comença a sortir un fluïd de color rosa, i es va unint, formant una figura que sembla una persona, pero de persona té poc, és un monstre?.")
    time.sleep(3)
    print("Un cop el monstre s'ha format al 100%, obre els ulls i... ")
    time.sleep(3)
    print("Et llença un raig que et converteix amb xocolata i es comença a divertir com si fossis el seu amic, però de sobte...")
    time.sleep(3)
    print(f"Comença a llançar-te boles d'energia fins que desapareixes, en els teus últims sospirs et fixes que el monstre ha absorbit la teva energia, i ell se'n va a lluitar contra en {enemic}.")
elif desició == 2: 
    print("Vas caminant pel camí número 2 i de sobte...")
    time.sleep(3)
    print("El terra comença a tremolar i de les esquerdes surt un cofre, i decideixes obrir-lo, del cofre surt... ")
    time.sleep(3)
    print("Et fixes que al fons, hi ha unes 7 esferes de color taronja amb cada una un nombre d'estrelles de l'1 al 7, i un paper que diu: ")
    time.sleep(3)
    print("Si al drac místic vols cridar, les set boles hauràs de juntar i el seu nom cridar.")
    time.sleep(3)
    print("Decideixes ajuntar totes les boles i cridar un nom que estava escrit al paper amb una lletra minúscula, aquest nom és: Joku ")
    time.sleep(3)
    print("Crides amb totes les teves forces: Joku!!!")
    time.sleep(3)
    print("De sobte de les 7 boles comença a emergir un drac de color vermell que et complirà 10 desitjos.")
    time.sleep(3)
    print(f"I tu {nom} com ets tan intel·ligent, desideixes 9 dels desitjos per afavorir a la teva persona, per exemple (riqueses, una casa nova), però a l'últim desitg...")
    time.sleep(3)
    print(f"Demanes una vestimenta i armes de foc per a combatre a {enemic}, i corrents vas on aquell tros d'ase ha capturat a tota la teva família i d'un tir al pit el mates, acabant amb tot el seu regnat i la bacteria {bacteria}.")
    time.sleep(3)
    print(f"Has guanyat {nom}, enhorabona!!!.")
elif desició == "Cap": #Cas de fugida
    print("Has decidit fugir, la teva persona serà recordada per ser un maleït egoista i covard per només pensar en la teva persona, i de sobte surt un ésser humà darrer la pedra, i et mata d'un tir a la columna vertebral.")